### ISSUE TITLE
Service not install on non-english Windows 10

### ISSUE THREAD

**Issue by sergserg2** [darkbrain-fc/HardwareSupervisor#5]
This is some problem with credentials or maybe non-english locales?

from EventViewer:
```
- <EventData>
  <Data>Aplikacja: HardwareSupervisor.exe Wersja architektury: v4.0.30319
Opis: proces został przerwany z powodu nieobsłużonego wyjątku. Informacje o wyjątku:
System.Security.Principal.IdentityNotMappedException w
System.Security.Principal.NTAccount.Translate(System.Security.Principal.IdentityReferenceCollection, System.Type, Boolean) w
System.Security.Principal.NTAccount.Translate(System.Type) w 
System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(System.Security.AccessControl.AccessControlModification, System.Security.AccessControl.AccessRule, Boolean ByRef) w 
System.Security.AccessControl.CommonObjectSecurity.AddAccessRule(System.Security.AccessControl.AccessRule) w 
ConfigurationManager.SettingConfigFilePermissions(System.String) w ConfigurationManager.Init() w 
HardwareSupervisor.Service.OnStart(System.String[]) w 
System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(System.Object) w 
System.ServiceProcess.ServiceBase.Run(System.ServiceProcess.ServiceBase[]) w HardwareSupervisor.Program.Main()
</Data> 
  </EventData>
```

**Comment by darkbrain-fc** [comment]
Hmm interesting. I don't think it can be a locale problems cause I have an
Italian OS. Btw at starting point the service will give write permissions
to everyone that has access to the machine at it's config file; this just
to be able to configure it without any frustrating administration
permissions. So try to check if config.yml file is there (in Hardware
Supervisor folder) and in case try to create one by yourself. Also try to
give a look at log file that you can find in same config file folder, maybe
you can find the stacktrace.
Bye

Il sab 22 gen 2022, 17:24 dziobak ***@***.***> ha scritto:

**Comment by sergserg2** [comment]
Yesterday, when i couldn't install the service via installer i did it manually (by unpacking msi to apropriate directory and adding service by sc.exe). In this case, starting the service gave the error (eventviewer):
The Hardware Supervisor Service has terminated; the following error has occurred:
An exception occurred in the service while handling the control request.

Log file in the directory has not been created.

**Comment by sergserg2** [comment]
There is also error from .NET runtime about not handled exception:

```
Aplikacja: HardwareSupervisor.exe
Wersja architektury: v4.0.30319
Opis: proces został przerwany z powodu nieobsłużonego wyjątku.
Informacje o wyjątku: System.Security.Principal.IdentityNotMappedException
 w System.Security.Principal.NTAccount.Translate(System.Security.Principal.IdentityReferenceCollection, System.Type, Boolean)
w System.Security.Principal.NTAccount.Translate(System.Type)
w System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(System.Security.AccessControl.AccessControlModification, System.Security.AccessControl.AccessRule, Boolean ByRef)
w System.Security.AccessControl.CommonObjectSecurity.AddAccessRule(System.Security.AccessControl.AccessRule)
w ConfigurationManager.SettingConfigFilePermissions(System.String)
w ConfigurationManager.Init()
w HardwareSupervisor.Service.OnStart(System.String[])
w System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(System.Object)
w System.ServiceProcess.ServiceBase.Run(System.ServiceProcess.ServiceBase[])
w HardwareSupervisor.Program.Main()
```

**Comment by sergserg2** [comment]
I think there is problem with non-english name for WMI groups. You use group by name (Configuration.cs line 60), not by sid. In my version of Windows 10 there is no english "Authenticated Users"
![obraz](https://user-images.githubusercontent.com/31377653/150674279-6154d4da-edc2-41f9-b58d-48fe5dca89df.png)

also look here http://polluxhieu.blogspot.com/2017/07/how-to-resolve-systemsecurityprincipali.html

**Comment by darkbrain-fc** [comment]
https://github.com/darkbrain-fc/HardwareSupervisor/tree/Configuration/FixLocaleGroup
https://github.com/darkbrain-fc/HardwareSupervisor/releases/tag/0.3.1

**Comment by sergserg2** [comment]
Great, service installed without problems and work
![obraz](https://user-images.githubusercontent.com/31377653/150692864-46de1a58-4966-44cc-9f08-7df55c0b0c4e.png)

**Comment by darkbrain-fc** [comment]
Nice! Thanks to your issue and analysis
